config/routes.rb
Finalproject::Application.routes.draw do
  resources :items

  resources :wishlists do
    member do
      put 'checkout'
    end
  end
  resources :books

  get "session/sign_in"

  get "session/sign_out"

  post "session/sign_in"
  
  post "session/sign_out"

  resources :users

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
	has_many :books, :through => :items
  	has_many :items, :dependent => :destroy
	belongs_to :user
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  # GET /wishlists
  # GET /wishlists.json
  def index
    @wishlists = Wishlist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wishlists }
    end
  end

  # GET /wishlists/1
  # GET /wishlists/1.json
  def show
    @wishlist = Wishlist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wishlist }
    end
  end

  # GET /wishlists/new
  # GET /wishlists/new.json
  def new
    @wishlist = Wishlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wishlist }
    end
  end

  # GET /wishlists/1/edit
  def edit
    @wishlist = Wishlist.find(params[:id])
  end

  # POST /wishlists
  # POST /wishlists.json
  def create
    @wishlist = Wishlist.new(params[:wishlist])
    @wishlist.user_id = session[:user_id]
    if @wishlist.save
      session[:wishlist_id] = @wishlist.id
      redirect_to @wishlist, :notice => 'Wishlist was successfully created.'
    else
      render :action => "new"
    end
  end

  # PUT /wishlists/1
  # PUT /wishlists/1.json
  def update
    @wishlist = Wishlist.find(params[:id])

    respond_to do |format|
      if @wishlist.update_attributes(params[:wishlist])
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlists/1
  # DELETE /wishlists/1.json
  def destroy
    @wishlist = Wishlist.find(params[:id])
    @wishlist.destroy
    session[:wishlist_id] = nil
    redirect_to root_url
  end

    # PUT /carts/1/checkout  
  def checkout
    if session[:wishlist_id].nil? then
      redirect_to root_url
    else
      @wishlist = Wishlist.find(session[:wishlist_id])
      @wishlist.destroy
      session[:wishlist_id] = nil
    end
  end   


end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_form.html.erb
<%= form_for(@wishlist) do |f| %>
  <% if @wishlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wishlist.errors.count, "error") %> prohibited this wishlist from being saved:</h2>

      <ul>
      <% @wishlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishlists/checkout.html.erb
<p id="notice"><%= notice %></p>
<p>The <%= @wishlist.name %> wishlist has been added to the cart!</p>
<p><%= link_to 'Return to the welcome page', root_path %></p>

app/views/wishlists/edit.html.erb
<h1>Editing wishlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @wishlist %> |
<%= link_to 'Back', wishlists_path %>

app/views/wishlists/index.html.erb
<h1>Listing wishlists</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wishlists.each do |wishlist| %>
  <tr>
    <td><%= wishlist.name %></td>
    <td><%= link_to 'Show', wishlist %></td>
    <td><%= link_to 'Edit', edit_wishlist_path(wishlist) %></td>
    <td><%= link_to 'Destroy', wishlist, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wishlist', new_wishlist_path %>

app/views/wishlists/new.html.erb
<h1>New wishlist</h1>

<%= render 'form' %>

<%= link_to 'Back', wishlists_path %>

app/views/wishlists/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @wishlist.name %>
</p>
<p id="alert"><%= alert %></p>

<p>
 <%= form_for(Item.new) do |f| %>
   <div>
   <span class="field">
     <%= f.label :book_id %>
     <%= f.select :book_id,
                  Book.all.collect{|p| [p.name, p.id]}.sort %>
   </span>
   <span class="field">
     <%= f.label :quantity_ordered %>
     <%= f.number_field :quantity_ordered %>
   </span>
   <span class="actions">
     <%= f.submit "Add item to wishlist" %>
   </span>
   </div>
  <% end %>
</p>

<p>
  <% if @wishlist.items.count > 0 then %>
    <b>Wishlist items:</b>
    <table>
      <tr>
        <th>Item name</th>
        <th>Description</th>
        <th>Quantity</th>
        <th>Unit price</th>
        <th>Extended price</th>
      </tr>
      <% @wishlist.items.each do |item| %>
        <tr>
          <td><%= item.book.name %></td>
          <td><%= item.book.description %></td>
          <td><%= item.quantity_ordered %></td>
          <td><%= item.book.unit_price %></td>
          <td><%= item.extended_price %></td>
          <td><%= link_to 'Remove item', item,
               :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
    Wishlist is empty.
  <% end %>
</p>

<p>
  <% if @wishlist.items.count > 0 then %>
    <%= link_to 'Add items to cart', checkout_wishlist_path(@wishlist),
                :method => :put %> |
  <% end %> 
  <%= link_to 'List books', books_path %> |
  <%= link_to 'Change wishlist name', edit_wishlist_path(@wishlist) %> |
  <%= link_to 'Delete the wishlist', @wishlist,
              :confirm => 'Are you sure?', :method => :delete %>
</p>